# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb6b2a76bb6c59dc1ad120ec04ca3be1262d53b3247f5b4ae42fff1b2f77c7817e0a122da386370ded716905efea3123fcf1be50eb12f1f7795b254a4456361

test:
  secret_key_base: f9400fa2a2dab1aead6913bd217847dcaab23fdf05347c8432b7e25fcfb12ba7702051fcd80ecfc497d879ea640814dd8242bd73bb129b4d977ad0646c1f1967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
